#!/usr/bin/env python3
"""
Memory admission gate (.jarvis/memory/) — runs in the pre-commit hook.

The quality of the shared memory is lost at WRITE time, not at read time:
memories without `estado:`, 100+ line reports and log-style titles
("audit 2026-07-18") entered the corpus unguarded, and the health linter
only reported it afterwards, when nobody processes the signal. This guard is
the twin of guard_propiedad/scan_secretos: it validates the CONTRACT of a
memory before it enters the repo, with one-line fix messages.

Rules (all with a trivial fix):
  - Complete frontmatter: titulo, tags, categoria, estado (vigente|obsoleta|
    lapida|archivo). Without it, recall/lint/INDEX handle it blindly.
  - Body ≤ 150 non-blank lines (more than that is a report: distill it).
  - NEW memory: no date embedded in the slug/title (a memory is
    knowledge, not a log entry — the date goes in creado:) and with
    `resumen:` (the line that recall injects into the agents' prompt).

Fails OPEN (unexpected error → allow) and exempts autogenerated content
(INDEX.md, lecciones-del-enjambre.md). Legitimate escape hatch: --no-verify.
Pure stdlib, no backend imports (runs in any clone).
"""
import re
import subprocess
import sys

_FRONT_RE  = re.compile(r'^---\s*\n(.*?)\n---\s*\n?', re.DOTALL)
_TAGS_RE   = re.compile(r'^tags:\s*\[([^\]]*)\]', re.MULTILINE)
_CAMPO_RE  = {k: re.compile(rf'^{k}:\s*(.+)$', re.MULTILINE)
              for k in ('titulo', 'categoria', 'estado', 'resumen')}
# Log pattern: year-month (2026-07). A bare year ("frames 2026") does not count.
_FECHA_RE  = re.compile(r'20\d{2}-\d{2}')
_ESTADOS   = {'vigente', 'obsoleta', 'lapida', 'archivo'}
_MAX_LINEAS = 150
_EXENTOS   = {'INDEX.md', 'lecciones-del-enjambre.md'}
_MEM_DIR   = '.jarvis/memory/'


def es_exento(path):
    return path.rsplit('/', 1)[-1] in _EXENTOS


def es_memoria(path):
    return path.startswith(_MEM_DIR) and path.endswith('.md') and not es_exento(path)


def _campo(front, k):
    m = _CAMPO_RE[k].search(front)
    return m.group(1).strip() if m else ''


def validar(slug, src, es_nueva):
    """List of contract violations ([] = admissible memory)."""
    m = _FRONT_RE.match(src or '')
    if not m:
        return ["no frontmatter — start the file with the `---` block from the protocol"]
    front, cuerpo = m.group(1), src[m.end():]
    v = []
    if not _campo(front, 'titulo'):
        v.append("missing `titulo:` in the frontmatter")
    mt = _TAGS_RE.search(front)
    if not (mt and [t for t in mt.group(1).split(',') if t.strip()]):
        v.append("missing `tags: [tag1, tag2]` in the frontmatter")
    if not _campo(front, 'categoria'):
        v.append("missing `categoria:` in the frontmatter (one from the protocol)")
    estado = _campo(front, 'estado').lower()
    if not estado:
        v.append("missing `estado:` in the frontmatter (vigente|obsoleta|lapida|archivo)")
    elif estado not in _ESTADOS:
        v.append(f"`estado: {estado}` invalid (vigente|obsoleta|lapida|archivo)")
    if es_nueva:
        # The line limit only blocks NEW memories: editing a long legacy one
        # (adding estado:, a finding) cannot require rewriting it — that pushes
        # toward --no-verify. Long legacy files are flagged by the lint.
        lineas = len([l for l in cuerpo.splitlines() if l.strip()])
        if lineas > _MAX_LINEAS:
            v.append(f"cuerpo de {lineas} líneas (máx {_MAX_LINEAS}) — eso es un informe: "
                     "destilá el hecho y punto")
        if _FECHA_RE.search(slug) or _FECHA_RE.search(_campo(front, 'titulo')):
            v.append("fecha embebida en el slug/título — una memoria no es bitácora: "
                     "la fecha va en `creado:`/`actualizado:`")
        if not _campo(front, 'resumen'):
            v.append("missing `resumen:` (one line with the fact — it's what recall "
                     "injects into the other agents' prompt)")
    return v


def memorias_staged():
    """[(path, es_nueva, contenido_staged)] of the memories in the index.
    Validates the STAGED version (git show :path), not the working-tree one."""
    salida = subprocess.run(
        ['git', 'diff', '--cached', '--name-status', '--diff-filter=AM'],
        capture_output=True, text=True, timeout=10).stdout
    out = []
    for linea in salida.splitlines():
        partes = linea.split('\t')
        if len(partes) < 2:
            continue
        status, path = partes[0], partes[-1]
        if not es_memoria(path):
            continue
        show = subprocess.run(['git', 'show', f':{path}'],
                              capture_output=True, text=True, timeout=10)
        if show.returncode != 0:
            continue
        out.append((path, status.startswith('A'), show.stdout))
    return out


def memorias_en_rango(viejo, nuevo):
    """[(path, es_nueva, contenido_en_nuevo)] of the memories touched in the
    outgoing range — the pre-push twin: catches what was committed with --no-verify."""
    salida = subprocess.run(
        ['git', 'diff', '--name-status', '--diff-filter=AM', f'{viejo}..{nuevo}'],
        capture_output=True, text=True, timeout=15).stdout
    out = []
    for linea in salida.splitlines():
        partes = linea.split('\t')
        if len(partes) < 2:
            continue
        status, path = partes[0], partes[-1]
        if not es_memoria(path):
            continue
        show = subprocess.run(['git', 'show', f'{nuevo}:{path}'],
                              capture_output=True, text=True, timeout=10)
        if show.returncode != 0:
            continue
        out.append((path, status.startswith('A'), show.stdout))
    return out


def _reportar(items, origen):
    fallo = 0
    for path, es_nueva, src in items:
        slug = path.rsplit('/', 1)[-1][:-3]
        for violacion in validar(slug, src, es_nueva):
            print(f"✖ MEMORY {path}: {violacion}")
            fallo = 1
    if fallo:
        print(f"  (.jarvis/memory/ contract in {origen} — see protocol in "
              "CLAUDE.md; legitimate false positive: git commit --no-verify)")
    return fallo


def main():
    try:
        if len(sys.argv) >= 4 and sys.argv[1] == '--rango':
            return _reportar(memorias_en_rango(sys.argv[2], sys.argv[3]), 'the push')
        return _reportar(memorias_staged(), 'the commit')
    except Exception:
        return 0     # fails OPEN: a bug here never bricks the commits


if __name__ == '__main__':
    sys.exit(main())
